// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectC.Server.Data;

#nullable disable

namespace ProjectC.Server.Migrations
{
    [DbContext(typeof(ProjectCDbContext))]
    [Migration("20230710214956_AddFlagForWorkflowActionRequests")]
    partial class AddFlagForWorkflowActionRequests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectC.Server.Data.Entities.RequestEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ForWorkflowAction")
                        .HasColumnType("bit");

                    b.Property<string>("JsonBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JsonHeaders")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RequestRuleId")
                        .HasColumnType("int");

                    b.Property<int?>("WebhookRuleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestRuleId");

                    b.HasIndex("WebhookRuleId");

                    b.ToTable("RequestEvent", (string)null);
                });

            modelBuilder.Entity("ProjectC.Server.Data.Entities.RequestRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResponseDelay")
                        .HasColumnType("int");

                    b.Property<string>("ResponseHeaders")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResponseStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RequestRule", (string)null);
                });

            modelBuilder.Entity("ProjectC.Server.Data.Entities.WebhookRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RedirectUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WebhookRule", (string)null);
                });

            modelBuilder.Entity("ProjectC.Server.Data.Entities.Workflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Workflow", (string)null);
                });

            modelBuilder.Entity("ProjectC.Server.Data.Entities.WorkflowAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestRuleId")
                        .HasColumnType("int");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResponseDelay")
                        .HasColumnType("int");

                    b.Property<string>("ResponseHeaders")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResponseStatus")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestRuleId");

                    b.HasIndex("WorkflowId");

                    b.ToTable("WorkflowAction", (string)null);
                });

            modelBuilder.Entity("ProjectC.Server.Data.Entities.WorkflowStorage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyIdentifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId")
                        .IsUnique();

                    b.ToTable("WorkflowStorage", (string)null);
                });

            modelBuilder.Entity("ProjectC.Server.Data.Entities.RequestEvent", b =>
                {
                    b.HasOne("ProjectC.Server.Data.Entities.RequestRule", null)
                        .WithMany("RequestEvents")
                        .HasForeignKey("RequestRuleId");

                    b.HasOne("ProjectC.Server.Data.Entities.WebhookRule", null)
                        .WithMany("RequestEvents")
                        .HasForeignKey("WebhookRuleId");
                });

            modelBuilder.Entity("ProjectC.Server.Data.Entities.WorkflowAction", b =>
                {
                    b.HasOne("ProjectC.Server.Data.Entities.RequestRule", "RequestRule")
                        .WithMany("WorkflowActions")
                        .HasForeignKey("RequestRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectC.Server.Data.Entities.Workflow", null)
                        .WithMany("WorkflowActions")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestRule");
                });

            modelBuilder.Entity("ProjectC.Server.Data.Entities.WorkflowStorage", b =>
                {
                    b.HasOne("ProjectC.Server.Data.Entities.Workflow", null)
                        .WithOne("WorkflowStorage")
                        .HasForeignKey("ProjectC.Server.Data.Entities.WorkflowStorage", "WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectC.Server.Data.Entities.RequestRule", b =>
                {
                    b.Navigation("RequestEvents");

                    b.Navigation("WorkflowActions");
                });

            modelBuilder.Entity("ProjectC.Server.Data.Entities.WebhookRule", b =>
                {
                    b.Navigation("RequestEvents");
                });

            modelBuilder.Entity("ProjectC.Server.Data.Entities.Workflow", b =>
                {
                    b.Navigation("WorkflowActions");

                    b.Navigation("WorkflowStorage");
                });
#pragma warning restore 612, 618
        }
    }
}
